package main

import (
	"strings"
	"testing"
)

const day7TestInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func TestDay7a_Example(t *testing.T) {
	expect := 21
	result := day7a(strings.SplitSeq(day7TestInput, "\n"))
	if result != expect {
		t.Errorf("expected %d, got %d", expect, result)
	}
}

func TestDay7a(t *testing.T) {
	input := readlines("./inputs/day07.txt")
	expect := 1555
	result := day7a(input)
	if result != expect {
		t.Errorf("expected %d, got %d", expect, result)
	}
}

func TestDay7b_Example(t *testing.T) {
	tt := []struct {
		input  string
		expect int
	}{
		{day7TestInput, 40},
		{`.......S.......
...............
.......^.......
...............`, 2},
		{`.......S.......
...............
.......^.......
...............
......^.^......
...............`, 4},
		{`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............`, 8},
		{`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............`, 13},
	}

	for _, tc := range tt {
		result := day7b(strings.SplitSeq(tc.input, "\n"))
		if result != tc.expect {
			t.Errorf("expected %d, got %d", tc.expect, result)
		}
	}
}

func TestDay7b(t *testing.T) {
	input := readlines("./inputs/day07.txt")
	expect := 12895232295789
	result := day7b(input)
	if result != expect {
		t.Errorf("expected %d, got %d", expect, result)
	}
}
