package main

import (
	"strings"
	"testing"
)

const day7TestInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func TestDay7a_Example(t *testing.T) {
	expect := 21
	result := day7a(strings.SplitSeq(day7TestInput, "\n"))
	if result != expect {
		t.Errorf("expected %d, got %d", expect, result)
	}
}

func TestDay7a(t *testing.T) {
	input := readlines("./inputs/day07.txt")
	expect := 1555
	result := day7a(input)
	if result != expect {
		t.Errorf("expected %d, got %d", expect, result)
	}
}
